version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: date-fns
    versions:
    - 2.17.0
    - 2.18.0
    - 2.19.0
    - 2.20.0
    - 2.20.1
    - 2.20.2
    - 2.20.3
    - 2.21.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: jsdom
    versions:
    - 16.5.0
    - 16.5.1
    - 16.5.2
  - dependency-name: sinon
    versions:
    - 10.0.0
    - 9.2.4
  - dependency-name: dompurify
    versions:
    - 2.2.7
  - dependency-name: mocha
    versions:
    - 8.3.0
    - 8.3.1
  - dependency-name: nock
    versions:
    - 13.0.10
    - 13.0.6
    - 13.0.7
    - 13.0.8
    - 13.0.9
  - dependency-name: node-schedule
    versions:
    - 1.3.3
